function reportData(){
  const pid=state.reportProjectId||"";
  const projects=pid?state.projects.filter(p=>p.id===pid):state.projects;
  const range=(items,field)=>items.filter(item=>{const v=item[field];if(!v)return true;if(state.reportFromDate&&v<state.reportFromDate)return false;if(state.reportToDate&&v>state.reportToDate)return false;return true;});
  const correspondence=range(pid?state.correspondence.filter(i=>i.project_id===pid):state.correspondence,"letter_date");
  const actions=range(pid?state.actionItems.filter(i=>i.project_id===pid):state.actionItems,"created_at");
  const inspections=range(pid?state.inspections.filter(i=>i.project_id===pid):state.inspections,"inspection_date");
  const today=new Date();today.setHours(0,0,0,0);
  const openActions=actions.filter(i=>!["completed","cancelled"].includes(i.status));
  const overdueActions=openActions.filter(i=>i.due_date&&new Date(`${i.due_date}T00:00:00`)<today);
  const pendingVerification=state.actionProgressUpdates.filter(u=>u.verification_status==="pending"&&actions.some(a=>a.id===u.action_id));
  const openInspections=inspections.filter(i=>["open","under_compliance"].includes(i.status));
  const criticalInspections=inspections.filter(i=>["critical","high"].includes(i.severity));
  return{projects,correspondence,actions,inspections,openActions,overdueActions,pendingVerification,openInspections,criticalInspections};
}
function reportProjectName(id){const p=state.projects.find(x=>x.id===id);return p?.project_code||p?.project_name||"Project";}
function reportSummaryCards(d){return`<div class="report-kpi-grid"><div class="report-kpi"><span>Projects</span><strong>${d.projects.length}</strong></div><div class="report-kpi"><span>Correspondence</span><strong>${d.correspondence.length}</strong></div><div class="report-kpi"><span>Open actions</span><strong>${d.openActions.length}</strong></div><div class="report-kpi"><span>Open inspections</span><strong>${d.openInspections.length}</strong></div></div>`;}
function reportProjectTable(items){if(!items.length)return`<div class="empty-state"><h3>No projects found</h3></div>`;return`<div class="report-table-wrap"><table class="report-table"><thead><tr><th>Project</th><th>Highway</th><th>Status</th><th>Mode</th><th>Progress</th><th>Completion</th></tr></thead><tbody>${items.map(p=>{const h=state.highways.find(x=>x.id===p.highway_id);return`<tr><td><strong>${escapeHtml(p.project_name)}</strong><br>${escapeHtml(p.project_code||"")}</td><td>${escapeHtml(h?.nh_number||"—")}</td><td>${escapeHtml(p.status||"—")}</td><td>${escapeHtml(p.mode||"—")}</td><td>${Number(p.physical_progress_pct||0)}%</td><td>${formatDate(p.scheduled_completion_date)}</td></tr>`;}).join("")}</tbody></table></div>`;}
function reportActionTable(items){if(!items.length)return`<div class="empty-state"><h3>No actions found</h3></div>`;return`<div class="report-table-wrap"><table class="report-table"><thead><tr><th>Action</th><th>Project</th><th>Assignees</th><th>Priority</th><th>Status</th><th>Due</th><th>Claimed / Verified</th></tr></thead><tbody>${items.map(a=>{const assignees=actionAssigneesFor(a.id);const latest=actionUpdatesFor(a.id)[0];return`<tr><td>${escapeHtml(a.title)}</td><td>${escapeHtml(reportProjectName(a.project_id))}</td><td>${escapeHtml(assignees.map(x=>actionUserName(x.user_id)).join(", ")||"Unassigned")}</td><td>${escapeHtml(a.priority||"normal")}</td><td>${escapeHtml(actionStatusLabel(a.status))}</td><td>${formatDate(a.due_date)}</td><td>${latest?Number(latest.claimed_progress_percent||0):Number(a.verified_progress_percent||0)}% / ${Number(a.verified_progress_percent||0)}%</td></tr>`;}).join("")}</tbody></table></div>`;}
function reportCorrespondenceTable(items){if(!items.length)return`<div class="empty-state"><h3>No correspondence found</h3></div>`;return`<div class="report-table-wrap"><table class="report-table"><thead><tr><th>Date</th><th>Direction</th><th>Letter No.</th><th>Subject</th><th>From</th><th>To</th><th>Status</th></tr></thead><tbody>${items.map(i=>`<tr><td>${formatDate(i.letter_date)}</td><td>${escapeHtml(i.direction)}</td><td>${escapeHtml(i.letter_number||"—")}</td><td>${escapeHtml(i.subject||"—")}</td><td>${escapeHtml(i.from_party||"—")}</td><td>${escapeHtml(i.to_party||"—")}</td><td>${escapeHtml(correspondenceStatusLabel(i.status))}</td></tr>`).join("")}</tbody></table></div>`;}
function reportInspectionTable(items){if(!items.length)return`<div class="empty-state"><h3>No inspections found</h3></div>`;return`<div class="report-table-wrap"><table class="report-table"><thead><tr><th>Date</th><th>Project</th><th>Type</th><th>Chainage</th><th>Severity</th><th>Status</th><th>Compliance due</th></tr></thead><tbody>${items.map(i=>`<tr><td>${formatDate(i.inspection_date)}</td><td>${escapeHtml(reportProjectName(i.project_id))}</td><td>${escapeHtml((i.inspection_type||"general").replaceAll("_"," "))}</td><td>${escapeHtml(chainageLabel(i))}</td><td>${escapeHtml(i.severity||"normal")}</td><td>${escapeHtml(inspectionStatusLabel(i.status))}</td><td>${formatDate(i.compliance_due_date)}</td></tr>`).join("")}</tbody></table></div>`;}
function reportExceptions(d){const rows=[...d.overdueActions.map(i=>({title:`Overdue action: ${i.title}`,detail:`${reportProjectName(i.project_id)} · Due ${formatDate(i.due_date)}`,value:"Overdue"})),...d.pendingVerification.map(u=>{const a=state.actionItems.find(x=>x.id===u.action_id);return{title:`Pending verification: ${a?.title||"Action"}`,detail:`${actionUserName(u.submitted_by)} claimed ${u.claimed_progress_percent}%`,value:"Pending"};}),...d.criticalInspections.map(i=>({title:`${i.severity} inspection: ${(i.inspection_type||"general").replaceAll("_"," ")}`,detail:`${reportProjectName(i.project_id)} · ${chainageLabel(i)}`,value:inspectionStatusLabel(i.status)}))];if(!rows.length)return`<div class="empty-state" style="min-height:120px;padding:24px;"><h3>No urgent exceptions</h3><p>No overdue, pending-verification or critical inspection items.</p></div>`;return`<div class="report-status-list">${rows.map(r=>`<div class="report-status-row"><div><strong>${escapeHtml(r.title)}</strong><span>${escapeHtml(r.detail)}</span></div><span class="status-pill pending">${escapeHtml(r.value)}</span></div>`).join("")}</div>`;}
function reportsTemplate(){const d=reportData();const p=state.reportProjectId?state.projects.find(x=>x.id===state.reportProjectId):null;return`<div class="app-shell">${appHeader()}${sidebar("reports")}<main class="main-content reports-page"><div class="breadcrumb"><span>Dashboard</span><b>/</b>Reports</div><div class="report-toolbar"><div><h1 style="margin:0;font-size:35px;letter-spacing:-.035em;">Reports</h1><p style="margin:8px 0 0;color:var(--muted);">Project status, correspondence, actions, inspections and exception summaries.</p></div><div class="report-controls"><select id="reports-project-filter"><option value="">All projects</option>${state.projects.map(x=>`<option value="${x.id}" ${state.reportProjectId===x.id?"selected":""}>${escapeHtml(x.project_name)}</option>`).join("")}</select><input id="reports-from-date" type="date" value="${state.reportFromDate||""}"/><input id="reports-to-date" type="date" value="${state.reportToDate||""}"/><button class="btn secondary" id="reports-apply-filter">Apply</button><button class="btn secondary" id="reports-print-button">Print / Save PDF</button><button class="btn primary" id="reports-download-button">Download CSV</button></div></div><section class="admin-card"><div class="admin-card-heading"><div><h2>${p?escapeHtml(p.project_name):"Division Summary"}</h2><p>Current consolidated status.</p></div></div><div style="padding:18px 20px;">${reportSummaryCards(d)}</div></section><div class="report-grid"><section class="report-card"><div class="report-section-title"><h3>Project status</h3><span>${d.projects.length}</span></div>${reportProjectTable(d.projects)}</section><section class="report-card"><div class="report-section-title"><h3>Urgent exceptions</h3><span>${d.overdueActions.length+d.pendingVerification.length+d.criticalInspections.length}</span></div>${reportExceptions(d)}</section></div><section class="report-card"><div class="report-section-title"><h3>Action register</h3><span>${d.actions.length}</span></div>${reportActionTable(d.actions)}</section><section class="report-card"><div class="report-section-title"><h3>Correspondence register</h3><span>${d.correspondence.length}</span></div>${reportCorrespondenceTable(d.correspondence)}</section><section class="report-card"><div class="report-section-title"><h3>Inspection register</h3><span>${d.inspections.length}</span></div>${reportInspectionTable(d.inspections)}</section></main></div>`;}
function reportExportDate(value){
  if(!value) return "";
  const raw=String(value);
  const datePart=raw.match(/^\d{4}-\d{2}-\d{2}/)?.[0]||raw;
  return formatDate(datePart);
}
function csvEscape(v){const s=v==null?"":String(v);return`"${s.replaceAll('"','""')}"`;}
function downloadReportsCsv(){const d=reportData();const rows=[["Section","Project","Date","Reference/Type","Subject/Title","Status","Due/Progress"],...d.projects.map(p=>["Project",p.project_code||"",reportExportDate(p.sanction_date),p.mode||"",p.project_name,p.status,`${Number(p.physical_progress_pct||0)}%`]),...d.correspondence.map(c=>["Correspondence",reportProjectName(c.project_id),reportExportDate(c.letter_date),c.letter_number||"",c.subject||"",correspondenceStatusLabel(c.status),"" ]),...d.actions.map(a=>["Action",reportProjectName(a.project_id),reportExportDate(a.created_at),a.priority||"",a.title,actionStatusLabel(a.status),`${Number(a.verified_progress_percent||0)}% verified`]),...d.inspections.map(i=>["Inspection",reportProjectName(i.project_id),reportExportDate(i.inspection_date),i.inspection_type||"",i.observations||"",inspectionStatusLabel(i.status),reportExportDate(i.compliance_due_date)])];const csv=rows.map(r=>r.map(csvEscape).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`MARGDARSHI-report-${isoDateLocal(new Date())}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function renderReports(){root.innerHTML=`<div class="loading-screen"><span class="spinner dark"></span><p>Preparing reports...</p></div>`;try{[state.correspondence,state.actionItems,state.actionAssignees,state.actionProgressUpdates,state.inspections]=await Promise.all([getCorrespondence(),getActionItems(),getActionAssignees(),getActionProgressUpdates(),getInspections()]);root.innerHTML=reportsTemplate();bindReportsEvents();}catch(error){root.innerHTML=`<div class="loading-screen"><p>${escapeHtml(error.message)}</p></div>`;}}
function bindReportsEvents(){bindCommonEvents();document.querySelector("#reports-apply-filter")?.addEventListener("click",()=>{state.reportProjectId=document.querySelector("#reports-project-filter").value;state.reportFromDate=document.querySelector("#reports-from-date").value;state.reportToDate=document.querySelector("#reports-to-date").value;root.innerHTML=reportsTemplate();bindReportsEvents();});document.querySelector("#reports-print-button")?.addEventListener("click",()=>window.print());document.querySelector("#reports-download-button")?.addEventListener("click",downloadReportsCsv);}
